//! dark-withdrawal-bundle
//!
//! Assembles the complete on-chain withdrawal payload for the Dark Null privacy
//! stack.  Connects four existing primitives in one coherent pipeline:
//!
//! ```text
//!  User secret + value
//!        │
//!        ▼
//!  ┌─────────────────┐     dark-poseidon-bn254
//!  │  ShieldedNote   │  note_commitment(value, rand, recipient_key)
//!  │  commitment[32] │
//!  └────────┬────────┘
//!           │  append into
//!           ▼
//!  ┌─────────────────┐     dark-merkle-accumulator
//!  │  MerkleAcc      │  depth-16, SHA256 hash nodes
//!  │  root[32]       │
//!  └────────┬────────┘
//!           │  prove_membership → MerkleProofPath
//!           ▼
//!  ┌─────────────────────────────────────────┐
//!  │  WithdrawalBundle                       │
//!  │  nullifier[32]  = poseidon_bn254(...)   │
//!  │  merkle_root[32]                        │
//!  │  proof_bytes[256] = devnet-test prefix  │
//!  └────────┬────────────────────────────────┘
//!           │  instruction_data() → [u8; 352]
//!           ▼
//!  dark_bn254_gate on-chain program
//!  proof(256) || merkle_root(32) || nullifier(32) || amount_le8_pad24(32)
//! ```
//!
//! ## Devnet note
//!
//! `proof_bytes` is generated with the `[0xDE, 0xAD]` devnet prefix so it
//! passes the on-chain gate without a real trusted-setup Groth16 proof.  This
//! is intentional and documented — see `dark_bn254_gate/src/processor.rs`.
//!
//! mainnet_ready = false — devnet only until security audit.

#[allow(unused_imports)]
use dark_merkle_accumulator::{
    append_leaf, compute_leaf_hash, new_accumulator, MerkleAcc, MerkleProofPath,
};
use dark_poseidon_bn254::{note_commitment, nullifier_hash, withdraw_public_inputs_hash};
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};

// ── Public types ──────────────────────────────────────────────────────────────

/// A shielded note: a committed value that can be spent once.
///
/// The commitment is `poseidon_bn254(DOMAIN_COMMITMENT || value_le8 || randomness || recipient_key)`.
/// The note owner knows `(value, randomness, recipient_key)` and the leaf index in the tree.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ShieldedNote {
    /// The note commitment stored in the Merkle tree.
    pub commitment: [u8; 32],
    /// Value in lamports (SOL micro-units).
    pub value: u64,
    /// Randomness used to blind the commitment (prevents brute-force correlation).
    pub randomness: [u8; 32],
    /// Hash of the recipient's public key (keeps recipient off-chain).
    pub recipient_key: [u8; 32],
    /// Always false.
    pub mainnet_ready: bool,
}

/// The secret spend key tied to one ShieldedNote.
///
/// To spend the note the holder provides this along with the Merkle root.
/// The resulting nullifier is `poseidon_bn254(DOMAIN_NULLIFIER || commitment || note_secret || root)`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NoteSecret {
    /// `SHA256("dark-note-secret-v1" || recipient_secret)` — derived from the user's root key.
    pub note_secret: [u8; 32],
}

/// The complete payload needed to call `dark_bn254_gate` and then
/// `dark_nullifier_banks` in a single atomic transaction.
///
/// `instruction_data()` serialises this into the exact 352-byte wire format
/// expected by `dark_bn254_gate`.
///
/// Note: not `Serialize`/`Deserialize` — the 256-byte proof field exceeds
/// serde's array size limit.  Serialise `proof_bytes` as `Vec<u8>` if needed.
#[derive(Debug, Clone)]
pub struct WithdrawalBundle {
    /// The 32-byte nullifier preventing double-spend.
    pub nullifier: [u8; 32],
    /// Merkle root at the time of withdrawal.
    pub merkle_root: [u8; 32],
    /// 256-byte Groth16 proof blob.
    /// For devnet: `[0xDE, 0xAD, ...]` — accepted by the gate unconditionally.
    /// For mainnet: a real Groth16 proof generated by the trusted circuit.
    pub proof_bytes: [u8; 256],
    /// Value being withdrawn (in lamports).
    pub value: u64,
    /// Merkle inclusion proof for the commitment.
    pub merkle_proof: MerkleProofPath,
    /// Hash of all three public inputs — used for off-chain audit receipts.
    pub public_inputs_hash: [u8; 32],
    /// Always false.
    pub mainnet_ready: bool,
}

/// Errors from this crate.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum WithdrawalError {
    /// Zero recipient key — indicates a missing key derivation step.
    ZeroRecipientKey,
    /// Zero note secret — would produce an insecure nullifier.
    ZeroNoteSecret,
    /// Zero randomness — commitment would be deterministic and linkable.
    ZeroRandomness,
    /// Zero value — no funds to withdraw.
    ZeroValue,
    /// Could not prove membership (leaf index out of range).
    LeafNotInTree { leaf_index: usize, tree_size: usize },
    /// The commitment in the tree does not match the note.
    CommitmentMismatch,
}

impl std::fmt::Display for WithdrawalError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ZeroRecipientKey => write!(f, "recipient key is all-zero"),
            Self::ZeroNoteSecret => write!(f, "note secret is all-zero"),
            Self::ZeroRandomness => write!(f, "randomness is all-zero"),
            Self::ZeroValue => write!(f, "value is zero"),
            Self::LeafNotInTree {
                leaf_index,
                tree_size,
            } => write!(f, "leaf {} not in tree of size {}", leaf_index, tree_size),
            Self::CommitmentMismatch => write!(f, "commitment in tree does not match note"),
        }
    }
}

impl std::error::Error for WithdrawalError {}

// ── Core helpers ──────────────────────────────────────────────────────────────

/// Derive a `NoteSecret` from the recipient's root secret key.
///
/// Formula: `SHA256("dark-note-secret-v1" || root_secret)`
///
/// Domain separation prevents the same key being used for commitments and nullifiers.
pub fn derive_note_secret(root_secret: &[u8; 32]) -> NoteSecret {
    let mut h = Sha256::new();
    h.update(b"dark-note-secret-v1");
    h.update(root_secret.as_slice());
    NoteSecret {
        note_secret: h.finalize().into(),
    }
}

/// Create a new `ShieldedNote` from a value and recipient key.
///
/// `randomness` must be unique per note (use a securely-random 32-byte nonce).
pub fn create_note(
    value: u64,
    randomness: &[u8; 32],
    recipient_key: &[u8; 32],
) -> Result<ShieldedNote, WithdrawalError> {
    if value == 0 {
        return Err(WithdrawalError::ZeroValue);
    }
    if randomness == &[0u8; 32] {
        return Err(WithdrawalError::ZeroRandomness);
    }
    if recipient_key == &[0u8; 32] {
        return Err(WithdrawalError::ZeroRecipientKey);
    }
    let commitment = note_commitment(value, randomness, recipient_key);
    Ok(ShieldedNote {
        commitment,
        value,
        randomness: *randomness,
        recipient_key: *recipient_key,
        mainnet_ready: false,
    })
}

/// Compute the nullifier for a note given the Merkle root at spend time.
///
/// Formula: `poseidon_bn254(DOMAIN_NULLIFIER || commitment || note_secret || root)`
///
/// The root binds the nullifier to the exact tree snapshot, preventing
/// cross-snapshot replay.
pub fn compute_nullifier(
    note: &ShieldedNote,
    secret: &NoteSecret,
    root: &[u8; 32],
) -> Result<[u8; 32], WithdrawalError> {
    if secret.note_secret == [0u8; 32] {
        return Err(WithdrawalError::ZeroNoteSecret);
    }
    Ok(nullifier_hash(&note.commitment, &secret.note_secret, root))
}

/// Insert a note commitment into a Merkle accumulator as a leaf.
///
/// Returns the leaf hash (= `compute_leaf_hash(commitment)`).
/// The leaf index is `tree.leaves.len() - 1` after this call.
///
/// Caller must use the returned leaf hash and the matching index to prove
/// membership later.
pub fn deposit_note(
    tree: &mut MerkleAcc,
    note: &ShieldedNote,
) -> Result<[u8; 32], dark_merkle_accumulator::AccError> {
    append_leaf(tree, note.commitment.as_slice())
}

/// Build the complete withdrawal bundle.
///
/// # Arguments
/// * `note` — the note being withdrawn
/// * `secret` — the note's spend secret
/// * `tree` — the Merkle accumulator containing the note commitment
/// * `leaf_index` — position in the tree where the note commitment was inserted
///
/// # Devnet proof
///
/// The 256-byte proof field starts with `[0xDE, 0xAD]` and the rest is a
/// deterministic hash of the public inputs.  This is accepted by
/// `dark_bn254_gate` in devnet-test mode.  For production, replace with a
/// real Groth16 proof from the trusted circuit.
pub fn build_withdrawal(
    note: &ShieldedNote,
    secret: &NoteSecret,
    tree: &MerkleAcc,
    leaf_index: usize,
) -> Result<WithdrawalBundle, WithdrawalError> {
    // ── Validate ─────────────────────────────────────────────────────────────
    if secret.note_secret == [0u8; 32] {
        return Err(WithdrawalError::ZeroNoteSecret);
    }

    // ── Verify the commitment is in the tree ─────────────────────────────────
    let expected_leaf_hash = compute_leaf_hash(note.commitment.as_slice());
    let tree_leaf_hash =
        tree.leaves
            .get(leaf_index)
            .copied()
            .ok_or(WithdrawalError::LeafNotInTree {
                leaf_index,
                tree_size: tree.leaves.len(),
            })?;
    if tree_leaf_hash != expected_leaf_hash {
        return Err(WithdrawalError::CommitmentMismatch);
    }

    // ── Merkle proof ──────────────────────────────────────────────────────────
    let merkle_proof = dark_merkle_accumulator::prove_membership(tree, leaf_index).ok_or(
        WithdrawalError::LeafNotInTree {
            leaf_index,
            tree_size: tree.leaves.len(),
        },
    )?;
    let merkle_root = merkle_proof.root;

    // ── Nullifier ─────────────────────────────────────────────────────────────
    let nullifier = compute_nullifier(note, secret, &merkle_root)?;

    // ── Public inputs hash ────────────────────────────────────────────────────
    let public_inputs_hash = withdraw_public_inputs_hash(&merkle_root, &nullifier, note.value);

    // ── Devnet proof bundle ───────────────────────────────────────────────────
    // Build a structured devnet proof:
    //   bytes[0..2]   = [0xDE, 0xAD]  (devnet prefix — accepted unconditionally)
    //   bytes[2..34]  = public_inputs_hash (for auditability)
    //   bytes[34..66] = commitment         (links proof to this specific note)
    //   bytes[66..98] = nullifier           (prevents forging a different nullifier)
    //   bytes[98..256]= zeros
    let mut proof_bytes = [0u8; 256];
    proof_bytes[0] = 0xDE;
    proof_bytes[1] = 0xAD;
    proof_bytes[2..34].copy_from_slice(&public_inputs_hash);
    proof_bytes[34..66].copy_from_slice(&note.commitment);
    proof_bytes[66..98].copy_from_slice(&nullifier);
    // bytes[98..256] = zeros — devnet padding

    Ok(WithdrawalBundle {
        nullifier,
        merkle_root,
        proof_bytes,
        value: note.value,
        merkle_proof,
        public_inputs_hash,
        mainnet_ready: false,
    })
}

/// Serialise a `WithdrawalBundle` into the 352-byte instruction data format
/// expected by `dark_bn254_gate`:
///
/// ```text
/// [0..256]  proof_bytes        (Groth16 proof — devnet: [0xDE, 0xAD, ...])
/// [256..288] merkle_root       (32 bytes, big-endian)
/// [288..320] nullifier          (32 bytes)
/// [320..352] amount_bytes      (u64 little-endian in first 8 bytes, zero-padded to 32)
/// ```
pub fn instruction_data(bundle: &WithdrawalBundle) -> [u8; 352] {
    let mut data = [0u8; 352];
    data[0..256].copy_from_slice(&bundle.proof_bytes);
    data[256..288].copy_from_slice(&bundle.merkle_root);
    data[288..320].copy_from_slice(&bundle.nullifier);
    // Amount: u64 LE in bytes 0..8, zero-padded to 32
    data[320..328].copy_from_slice(&bundle.value.to_le_bytes());
    data
}

// ── Tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    const DEPTH: u8 = 4; // 16-leaf tree — enough for tests

    fn make_nonce(b: u8) -> [u8; 32] {
        let mut n = [0u8; 32];
        n[0] = b;
        n
    }

    fn make_root_secret(b: u8) -> [u8; 32] {
        let mut s = [0u8; 32];
        s[0] = b;
        s[1] = 0xFF;
        s
    }

    fn make_recipient_key(b: u8) -> [u8; 32] {
        let mut k = [0u8; 32];
        k[0] = 0xCC;
        k[1] = b;
        k
    }

    fn make_tree() -> MerkleAcc {
        new_accumulator(DEPTH, &make_nonce(0x01)).unwrap()
    }

    // ── Test 1: create note is deterministic ─────────────────────────────────
    #[test]
    fn test_create_note_deterministic() {
        let rk = make_recipient_key(1);
        let rand = make_nonce(0x77);
        let n1 = create_note(1_000_000, &rand, &rk).unwrap();
        let n2 = create_note(1_000_000, &rand, &rk).unwrap();
        assert_eq!(n1.commitment, n2.commitment);
        assert!(!n1.mainnet_ready);
    }

    // ── Test 2: different randomness → different commitment ──────────────────
    #[test]
    fn test_different_randomness_different_commitment() {
        let rk = make_recipient_key(2);
        let n1 = create_note(500_000, &make_nonce(0x01), &rk).unwrap();
        let n2 = create_note(500_000, &make_nonce(0x02), &rk).unwrap();
        assert_ne!(n1.commitment, n2.commitment);
    }

    // ── Test 3: different value → different commitment ───────────────────────
    #[test]
    fn test_different_value_different_commitment() {
        let rk = make_recipient_key(3);
        let rand = make_nonce(0xAA);
        let n1 = create_note(1_000_000, &rand, &rk).unwrap();
        let n2 = create_note(2_000_000, &rand, &rk).unwrap();
        assert_ne!(n1.commitment, n2.commitment);
    }

    // ── Test 4: zero value rejected ──────────────────────────────────────────
    #[test]
    fn test_zero_value_rejected() {
        let err = create_note(0, &make_nonce(0x01), &make_recipient_key(1)).unwrap_err();
        assert_eq!(err, WithdrawalError::ZeroValue);
    }

    // ── Test 5: zero randomness rejected ────────────────────────────────────
    #[test]
    fn test_zero_randomness_rejected() {
        let err = create_note(1_000, &[0u8; 32], &make_recipient_key(1)).unwrap_err();
        assert_eq!(err, WithdrawalError::ZeroRandomness);
    }

    // ── Test 6: nullifier is deterministic ──────────────────────────────────
    #[test]
    fn test_nullifier_deterministic() {
        let note = create_note(1_000_000, &make_nonce(0x10), &make_recipient_key(4)).unwrap();
        let secret = derive_note_secret(&make_root_secret(4));
        let root = [0xAB; 32];
        let n1 = compute_nullifier(&note, &secret, &root).unwrap();
        let n2 = compute_nullifier(&note, &secret, &root).unwrap();
        assert_eq!(n1, n2);
    }

    // ── Test 7: different root → different nullifier (root binding) ──────────
    #[test]
    fn test_different_root_different_nullifier() {
        let note = create_note(1_000_000, &make_nonce(0x11), &make_recipient_key(5)).unwrap();
        let secret = derive_note_secret(&make_root_secret(5));
        let n1 = compute_nullifier(&note, &secret, &[0xAB; 32]).unwrap();
        let n2 = compute_nullifier(&note, &secret, &[0xCD; 32]).unwrap();
        assert_ne!(
            n1, n2,
            "nullifier must be root-bound to prevent cross-snapshot replay"
        );
    }

    // ── Test 8: deposit inserts leaf into Merkle tree ────────────────────────
    #[test]
    fn test_deposit_inserts_leaf() {
        let mut tree = make_tree();
        let note = create_note(2_000_000, &make_nonce(0x20), &make_recipient_key(6)).unwrap();
        let root_before = tree.root;
        let leaf_hash = deposit_note(&mut tree, &note).unwrap();
        assert_ne!(tree.root, root_before, "root must change after insertion");
        assert_eq!(tree.leaves.len(), 1);
        assert_eq!(tree.leaves[0], leaf_hash);
    }

    // ── Test 9: full roundtrip — deposit then build withdrawal ──────────────
    #[test]
    fn test_full_withdrawal_roundtrip() {
        let mut tree = make_tree();
        let rk = make_recipient_key(7);
        let rand = make_nonce(0x33);
        let note = create_note(3_000_000, &rand, &rk).unwrap();
        let secret = derive_note_secret(&make_root_secret(7));

        let _leaf_hash = deposit_note(&mut tree, &note).unwrap();
        let bundle = build_withdrawal(&note, &secret, &tree, 0).unwrap();

        assert_ne!(bundle.nullifier, [0u8; 32], "nullifier must be non-zero");
        assert_eq!(bundle.merkle_root, tree.root);
        assert_eq!(bundle.value, 3_000_000);
        assert!(!bundle.mainnet_ready);

        // Merkle proof root must match tree root
        assert_eq!(bundle.merkle_proof.root, tree.root);
    }

    // ── Test 10: instruction_data has correct wire layout ────────────────────
    #[test]
    fn test_instruction_data_layout() {
        let mut tree = make_tree();
        let note = create_note(500_000, &make_nonce(0x44), &make_recipient_key(8)).unwrap();
        let secret = derive_note_secret(&make_root_secret(8));
        deposit_note(&mut tree, &note).unwrap();
        let bundle = build_withdrawal(&note, &secret, &tree, 0).unwrap();

        let ix = instruction_data(&bundle);

        // Total length
        assert_eq!(ix.len(), 352);
        // Proof starts at offset 0
        assert_eq!(&ix[0..256], &bundle.proof_bytes);
        // Devnet prefix
        assert_eq!(ix[0], 0xDE);
        assert_eq!(ix[1], 0xAD);
        // Merkle root at 256..288
        assert_eq!(&ix[256..288], &bundle.merkle_root);
        // Nullifier at 288..320
        assert_eq!(&ix[288..320], &bundle.nullifier);
        // Amount at 320..328 (LE u64)
        let amount = u64::from_le_bytes(ix[320..328].try_into().unwrap());
        assert_eq!(amount, 500_000u64);
        // Remaining 24 bytes of amount field are zero
        assert_eq!(&ix[328..352], &[0u8; 24]);
    }

    // ── Test 11: proof carries public inputs hash for auditability ──────────
    #[test]
    fn test_proof_carries_public_inputs_hash() {
        let mut tree = make_tree();
        let note = create_note(100_000, &make_nonce(0x55), &make_recipient_key(9)).unwrap();
        let secret = derive_note_secret(&make_root_secret(9));
        deposit_note(&mut tree, &note).unwrap();
        let bundle = build_withdrawal(&note, &secret, &tree, 0).unwrap();

        let ix = instruction_data(&bundle);
        // bytes[2..34] of proof = public_inputs_hash
        assert_eq!(&ix[2..34], &bundle.public_inputs_hash);
        // public_inputs_hash is non-zero
        assert_ne!(bundle.public_inputs_hash, [0u8; 32]);
    }

    // ── Test 12: two notes have different nullifiers ─────────────────────────
    #[test]
    fn test_two_notes_have_different_nullifiers() {
        let mut tree = make_tree();
        let s1 = derive_note_secret(&make_root_secret(10));
        let s2 = derive_note_secret(&make_root_secret(11));

        let n1 = create_note(100_000, &make_nonce(0x60), &make_recipient_key(10)).unwrap();
        let n2 = create_note(100_000, &make_nonce(0x61), &make_recipient_key(11)).unwrap();

        deposit_note(&mut tree, &n1).unwrap(); // leaf 0
        deposit_note(&mut tree, &n2).unwrap(); // leaf 1

        let b1 = build_withdrawal(&n1, &s1, &tree, 0).unwrap();
        let b2 = build_withdrawal(&n2, &s2, &tree, 1).unwrap();

        assert_ne!(
            b1.nullifier, b2.nullifier,
            "each note must produce a unique nullifier"
        );
    }

    // ── Test 13: wrong leaf index → LeafNotInTree ────────────────────────────
    #[test]
    fn test_wrong_leaf_index_rejected() {
        let mut tree = make_tree();
        let note = create_note(200_000, &make_nonce(0x70), &make_recipient_key(12)).unwrap();
        let secret = derive_note_secret(&make_root_secret(12));
        deposit_note(&mut tree, &note).unwrap(); // leaf 0

        // Try to prove leaf 5 (not inserted)
        let err = build_withdrawal(&note, &secret, &tree, 5).unwrap_err();
        assert!(matches!(
            err,
            WithdrawalError::LeafNotInTree {
                leaf_index: 5,
                tree_size: 1
            }
        ));
    }

    // ── Test 14: commitment mismatch → CommitmentMismatch ────────────────────
    #[test]
    fn test_commitment_mismatch_rejected() {
        let mut tree = make_tree();
        let note_a = create_note(300_000, &make_nonce(0x80), &make_recipient_key(13)).unwrap();
        let note_b = create_note(300_000, &make_nonce(0x81), &make_recipient_key(14)).unwrap();
        let secret = derive_note_secret(&make_root_secret(13));

        deposit_note(&mut tree, &note_a).unwrap(); // leaf 0 is note_a

        // Try to build a bundle for note_b but claim it's at leaf 0 (note_a's slot)
        let err = build_withdrawal(&note_b, &secret, &tree, 0).unwrap_err();
        assert_eq!(
            err,
            WithdrawalError::CommitmentMismatch,
            "must detect that note_b's commitment is not at leaf 0"
        );
    }

    // ── Test 15: derive_note_secret is deterministic ─────────────────────────
    #[test]
    fn test_derive_note_secret_deterministic() {
        let s = make_root_secret(99);
        let ns1 = derive_note_secret(&s);
        let ns2 = derive_note_secret(&s);
        assert_eq!(ns1.note_secret, ns2.note_secret);
        // Different root secrets → different note secrets
        let ns3 = derive_note_secret(&make_root_secret(100));
        assert_ne!(ns1.note_secret, ns3.note_secret);
    }
}
