import json
import pathlib
import sys
import unittest

ROOT = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from dna_x402.receipts import verify_signed_receipt  # noqa: E402


class ReceiptVerificationTests(unittest.TestCase):
    def test_rejects_tampered_receipt_vector(self) -> None:
        receipt = {
            "payload": {
                "receiptId": "00000000-0000-0000-0000-000000000000",
                "quoteId": "quote",
                "commitId": "commit",
                "settlement": "transfer",
                "amountAtomic": "1",
                "feeAtomic": "0",
                "totalAtomic": "1",
                "mint": "USDC",
                "recipient": "recipient",
                "payerCommitment32B": "00" * 32,
                "createdAt": "2026-05-14T00:00:00.000Z",
                "requestId": "request",
                "requestDigest": "11" * 32,
                "responseDigest": "22" * 32,
            },
            "prevHash": "0" * 64,
            "receiptHash": "f" * 64,
            "signerPublicKey": "11111111111111111111111111111111",
            "signature": "1111111111111111111111111111111111111111111111111111111111111111",
        }
        self.assertFalse(verify_signed_receipt(receipt))

    def test_accepts_runtime_vector_from_node_when_provided(self) -> None:
        vector = pathlib.Path(__file__).with_name("receipt-vector.json")
        if not vector.exists():
            self.skipTest("receipt-vector.json is generated by integration tests")
        receipt = json.loads(vector.read_text(encoding="utf-8"))
        self.assertTrue(verify_signed_receipt(receipt))


if __name__ == "__main__":
    unittest.main()
