/**
 * @parad0x_labs/session-channels
 *
 * Ephemeral Paid Sessions — batch N micro-actions into one x402 settlement.
 *
 * Problem: a Telegram bot running 200 tiny AI actions per hour would normally
 * fire 200 separate x402 payments. That is 200 Solana transactions.
 *
 * Solution: open a session channel once, record each action locally, close the
 * channel when done, then settle the entire batch with:
 *   1. One x402 payment (total fee)
 *   2. One Liquefy-compressed receipt batch (all action digests)
 *   3. One Solana receipt_anchor transaction
 *
 * Integration points:
 *   - @parad0x_labs/liquefy-receipts  →  compressReceipts, batchHash, buildAnchorIxData
 *   - DNA x402 facilitator            →  receives { scheme, token, payload, receipt }
 */

import { createHash, randomBytes } from "node:crypto";

// ─── Re-export Liquefy types so callers can import from one place ─────────────
// (runtime import kept optional to avoid hard dep if tree-shaking is used)

// ─── Core interfaces ──────────────────────────────────────────────────────────

/** A single action executed inside an open session. */
export interface SessionAction {
  /** Stable unique ID for this action (UUID-like hex, generated by recordAction). */
  actionId: string;
  /** Human-readable action type label, e.g. "llm-inference", "tool-call", "search". */
  actionType: string;
  /** Unix ms timestamp of when the action was executed. */
  executedAt: number;
  /** SHA-256 hex digest of the action result payload (prevents tampering). */
  resultDigest: string;
  /** Fee charged for this action, denominated in the session currency. */
  fee: number;
}

/** An ephemeral session channel between an AI agent and a provider. */
export interface SessionChannel {
  /** Globally unique session identifier (hex). */
  sessionId: string;
  /** Base58 or hex public key of the agent opening the session. */
  agentPubkey: string;
  /** Base58 or hex public key of the provider receiving payment. */
  providerPubkey: string;
  /** Unix ms timestamp of when the channel was opened. */
  openedAt: number;
  /** Hard cap on the number of actions this session allows. */
  maxActions: number;
  /** Price per action in the smallest unit of the chosen currency. */
  pricePerAction: number;
  /** Payment currency. USDC = stable, SOL = native. */
  currency: "USDC" | "SOL";
  /** Ordered log of all actions executed inside this session. */
  actions: SessionAction[];
  /** Channel lifecycle state. */
  status: "open" | "closed" | "settled";
}

// ─── Params for openSession ───────────────────────────────────────────────────

export interface OpenSessionParams {
  agentPubkey: string;
  providerPubkey: string;
  maxActions: number;
  pricePerAction: number;
  currency: "USDC" | "SOL";
}

// ─── Close result ─────────────────────────────────────────────────────────────

export interface CloseSessionResult {
  session: SessionChannel;
  totalFee: number;
  /** Hex-encoded SHA-256 of the ordered action-ID list — acts as a tamper-evident receipt. */
  receipt: string;
}

// ─── Settlement payload ───────────────────────────────────────────────────────

/**
 * Ready-to-submit settlement payload.
 *
 * Hand `x402Payment` to the DNA x402 facilitator.
 * Hand `anchorIxData` to the Solana receipt_anchor program
 *   (6HSRGivdYR5D7yTDy1TFMCM8h3LzXxRtKU1RA3RnCMRN).
 * Store `compressedReceiptBatch` off-chain (Arweave / IPFS / DB).
 */
export interface SettlementPayload {
  /** Session ID for correlation. */
  sessionId: string;
  /** Number of actions included. */
  actionCount: number;
  /** Total fee, denominated in session currency. */
  totalFee: number;
  /** Currency the totalFee is expressed in. */
  currency: "USDC" | "SOL";
  /**
   * Liquefy-compressed binary receipt batch.
   * Each row is a SessionAction serialised as an X402Receipt-compatible record.
   * Pass to compressReceipts() from @parad0x_labs/liquefy-receipts.
   */
  compressedReceiptBatch: Uint8Array;
  /**
   * SHA-256 hex of compressedReceiptBatch — the on-chain commitment.
   * Matches what buildAnchorIxData() will embed in the Solana tx.
   */
  batchHash: string;
  /**
   * 34-byte instruction data for the receipt_anchor program:
   *   [0x01][0x00][32 bytes SHA-256 commitment]
   * Constructed via buildAnchorIxData() from @parad0x_labs/liquefy-receipts.
   */
  anchorIxData: Uint8Array;
  /**
   * Minimal x402 payment envelope ready to POST to the facilitator.
   * The facilitator validates totalFee, then sends the on-chain USDC/SOL transfer.
   */
  x402Payment: {
    scheme: "exact";
    network: "solana-mainnet" | "solana-devnet";
    from: string;
    to: string;
    amount: number;
    currency: "USDC" | "SOL";
    sessionId: string;
    batchHash: string;
    actionCount: number;
  };
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

/** Generate a cryptographically random 16-byte hex ID. */
function newId(): string {
  return randomBytes(16).toString("hex");
}

/** SHA-256 hex of a UTF-8 string. */
function sha256hex(input: string): string {
  return createHash("sha256").update(input, "utf8").digest("hex");
}

/**
 * Columnar-compress an array of action records.
 *
 * We inline a minimal deflate-based compression here so the package has no
 * mandatory runtime dependency on @parad0x_labs/liquefy-receipts. Callers
 * who want full Liquefy compression should pass their own compressor via
 * buildSettlementPayload's optional `compress` parameter.
 *
 * The default implementation JSON-encodes the action array and returns it as
 * UTF-8 bytes — a valid (uncompressed) fallback that the anchor still hashes
 * correctly.
 */
function defaultCompress(actions: SessionAction[]): Uint8Array {
  return new TextEncoder().encode(JSON.stringify(actions));
}

// ─── Public API ───────────────────────────────────────────────────────────────

/**
 * Open a new ephemeral session channel.
 *
 * @example
 * const session = openSession({
 *   agentPubkey:    "AgentPubkey...",
 *   providerPubkey: "ProviderPubkey...",
 *   maxActions:     200,
 *   pricePerAction: 0.001,   // 0.001 USDC per action
 *   currency:       "USDC",
 * });
 */
export function openSession(params: OpenSessionParams): SessionChannel {
  if (params.maxActions < 1) {
    throw new RangeError("maxActions must be >= 1");
  }
  if (params.pricePerAction < 0) {
    throw new RangeError("pricePerAction must be >= 0");
  }
  if (!params.agentPubkey || !params.providerPubkey) {
    throw new TypeError("agentPubkey and providerPubkey are required");
  }

  return {
    sessionId:      newId(),
    agentPubkey:    params.agentPubkey,
    providerPubkey: params.providerPubkey,
    openedAt:       Date.now(),
    maxActions:     params.maxActions,
    pricePerAction: params.pricePerAction,
    currency:       params.currency,
    actions:        [],
    status:         "open",
  };
}

/**
 * Record a completed action inside an open session.
 *
 * Returns a new SessionChannel value — original is not mutated.
 *
 * @param session       The current channel state.
 * @param actionType    Label for the action, e.g. "llm-inference".
 * @param resultPayload The raw result (string / JSON-stringifiable). Its
 *                      SHA-256 is stored as resultDigest for tamper-evidence.
 * @throws If the session is not open or has reached maxActions.
 *
 * @example
 * session = recordAction(session, "llm-inference", responseText);
 */
export function recordAction(
  session: SessionChannel,
  actionType: string,
  resultPayload: string | object,
): SessionChannel {
  if (session.status !== "open") {
    throw new Error(`Cannot record action: session ${session.sessionId} is ${session.status}`);
  }
  if (session.actions.length >= session.maxActions) {
    throw new RangeError(
      `Session ${session.sessionId} has reached maxActions (${session.maxActions})`,
    );
  }

  const raw = typeof resultPayload === "string"
    ? resultPayload
    : JSON.stringify(resultPayload);

  const action: SessionAction = {
    actionId:     newId(),
    actionType,
    executedAt:   Date.now(),
    resultDigest: sha256hex(raw),
    fee:          session.pricePerAction,
  };

  return {
    ...session,
    actions: [...session.actions, action],
  };
}

/**
 * Close a session and compute its receipt.
 *
 * Marks the session as "closed". The session is not yet settled — call
 * buildSettlementPayload() to get the x402 + anchor submission data, then
 * mark the session as "settled" once confirmed on-chain.
 *
 * @returns CloseSessionResult with the updated session, totalFee, and receipt.
 * @throws If the session is already closed or settled.
 */
export function closeSession(session: SessionChannel): CloseSessionResult {
  if (session.status !== "open") {
    throw new Error(`Cannot close session ${session.sessionId}: already ${session.status}`);
  }

  const totalFee = session.actions.reduce((sum, a) => sum + a.fee, 0);

  // Tamper-evident receipt: SHA-256 of sorted action IDs + totalFee
  const receiptInput = session.actions.map(a => a.actionId).join("|")
    + `|total=${totalFee}|session=${session.sessionId}`;
  const receipt = sha256hex(receiptInput);

  const closed: SessionChannel = {
    ...session,
    status: "closed",
  };

  return { session: closed, totalFee, receipt };
}

/**
 * Build a settlement payload ready for Liquefy + receipt_anchor submission.
 *
 * Produces everything needed for a single-transaction settlement:
 *   - Liquefy-compressed receipt batch (or fallback JSON bytes)
 *   - SHA-256 batch hash for the on-chain anchor commitment
 *   - 34-byte anchorIxData for the receipt_anchor Solana program
 *   - x402 payment envelope for the DNA x402 facilitator
 *
 * @param session   A closed (or open) SessionChannel.
 * @param network   Solana network for the x402 payment.
 * @param compress  Optional custom compressor — pass `compressReceipts` from
 *                  @parad0x_labs/liquefy-receipts for full columnar compression.
 *                  Defaults to JSON encoding (lossless, no extra dep required).
 *
 * @example
 * // Basic usage (JSON fallback compression):
 * const payload = buildSettlementPayload(closedSession, "solana-mainnet");
 *
 * @example
 * // Full Liquefy compression:
 * import { compressReceipts } from "@parad0x_labs/liquefy-receipts";
 * const payload = buildSettlementPayload(closedSession, "solana-mainnet", compressReceipts);
 */
export function buildSettlementPayload(
  session: SessionChannel,
  network: "solana-mainnet" | "solana-devnet" = "solana-mainnet",
  compress?: (actions: SessionAction[]) => Uint8Array,
): SettlementPayload {
  if (session.actions.length === 0) {
    throw new Error(`Session ${session.sessionId} has no recorded actions to settle`);
  }

  const totalFee = session.actions.reduce((sum, a) => sum + a.fee, 0);

  // Compress the action log — use caller-supplied Liquefy or JSON fallback
  const compressor = compress ?? defaultCompress;
  const compressedReceiptBatch = compressor(session.actions);

  // SHA-256 commitment over the compressed bytes
  const hashHex = createHash("sha256").update(compressedReceiptBatch).digest("hex");

  // Build the 34-byte anchor instruction data:
  // [0x01][0x00][32 bytes SHA-256 commitment]
  const commitment32 = Buffer.from(hashHex, "hex");
  const anchorIxData = new Uint8Array(34);
  anchorIxData[0] = 0x01;
  anchorIxData[1] = 0x00;
  anchorIxData.set(commitment32, 2);

  return {
    sessionId:              session.sessionId,
    actionCount:            session.actions.length,
    totalFee,
    currency:               session.currency,
    compressedReceiptBatch,
    batchHash:              hashHex,
    anchorIxData,
    x402Payment: {
      scheme:      "exact",
      network,
      from:        session.agentPubkey,
      to:          session.providerPubkey,
      amount:      totalFee,
      currency:    session.currency,
      sessionId:   session.sessionId,
      batchHash:   hashHex,
      actionCount: session.actions.length,
    },
  };
}

/**
 * Mark a session as settled after the on-chain anchor tx has been confirmed.
 *
 * @param session         A closed SessionChannel.
 * @param anchorTxSig     The Solana transaction signature of the anchor tx.
 * @returns A new SessionChannel with status "settled".
 */
export function settleSession(
  session: SessionChannel,
  anchorTxSig: string,
): SessionChannel & { anchorTxSig: string } {
  if (session.status !== "closed") {
    throw new Error(
      `Cannot settle session ${session.sessionId}: expected "closed", got "${session.status}"`,
    );
  }
  return {
    ...session,
    status: "settled",
    anchorTxSig,
  };
}
