//! `k`-of-`n` guardian federation (Fedimint-style) — the decentralized point.
//!
//! The single mint secret `k` of [`crate::bdhke`] is replaced by a Shamir
//! sharing over the Ristretto scalar field, generated by a **DKG** (Feldman
//! verifiable secret sharing) so **no single guardian ever holds `k`**. Issuing
//! a token requires `k` guardians to each produce a *partial* blind signature;
//! Lagrange interpolation in the exponent reconstructs the BDHKE signature
//! `C_ = k·B_` without anyone learning `k`.
//!
//! ## What is and isn't decentralized here (be honest)
//! * **Decentralized:** the mint key. With threshold `t`, any `t` guardians can
//!   co-sign, fewer than `t` cannot, and no one party can over-issue or forge.
//!   The group public key `K = k·G` is fixed; the chain trusts `K`, not any
//!   single guardian.
//! * **This is a single-machine simulation of the federation** (all guardian
//!   shares are computed in one process for the e2e). The cryptography is the
//!   real threshold scheme; the *network transport* (each guardian on its own
//!   host, gossiping shares) is a documented follow-up — the math is what makes
//!   it trust-minimized, and that is real here.
//!
//! ## DKG (Feldman VSS, joint-Feldman)
//! Each guardian `i ∈ 1..=n` samples a degree-`t-1` polynomial `f_i` with
//! `f_i(0) = a_i` (its contribution to `k`). It publishes commitments
//! `A_{i,j} = a_{i,j}·G` and privately sends `f_i(j)` to guardian `j`. Each
//! guardian `j` verifies every received share against the public commitments,
//! then sets its key share to `s_j = Σ_i f_i(j)`. The joint secret is
//! `k = Σ_i a_i = Σ_i f_i(0)` (held by nobody) and the group key is
//! `K = Σ_i A_{i,0} = k·G`.
//!
//! ## Threshold blind signing
//! On a blinded point `B_`, each signer `j` returns `C_{j} = s_j·B_`. Any `t`
//! of them combine: `C_ = Σ_j λ_j·C_{j} = (Σ_j λ_j s_j)·B_ = k·B_`, where `λ_j`
//! are Lagrange coefficients at `x=0` for the chosen signer set. This is exactly
//! the single-mint `C_` — so the rest of BDHKE (unblind, redeem) is unchanged.
//!
//! ## Threshold DLEQ (so the on-chain redeem still works, key-blind)
//! The redeem needs a DLEQ that `C = k·Y` under `K = k·G`. We run a FROST-style
//! distributed Schnorr over the shared `k`: each of the `t` signers contributes
//! a nonce share `d_j`, the aggregate nonce is `D = Σ λ_j d_j` (in the exponent
//! via `R1 = Σ λ_j (d_j·G)`, `R2 = Σ λ_j (d_j·Y)`), the challenge `e` is the
//! Fiat–Shamir hash, and each signer returns `z_j = d_j + e·s_j`. The aggregate
//! `z = Σ λ_j z_j = D + e·k` is a valid DLEQ response under `k`. No guardian
//! reveals its share; the proof verifies under the group key `K`.

use crate::bdhke::hash_to_curve;
use crate::dleq::DleqProof;
use curve25519_dalek::constants::RISTRETTO_BASEPOINT_POINT as G;
use curve25519_dalek::ristretto::{CompressedRistretto, RistrettoPoint};
use curve25519_dalek::scalar::Scalar;
use rand::rngs::OsRng;
use rand::RngCore;
use sha2::{Digest, Sha512};

/// Sample a uniform scalar from the OS RNG.
///
/// curve25519-dalek 3.2.1 binds `Scalar::random` to rand_core 0.5's `CryptoRng`,
/// but the workspace's `rand 0.8` ships rand_core 0.6 — the two `CryptoRng`
/// traits are distinct, so `rand_scalar_os()` won't type-check. We
/// instead fill 64 OS-random bytes and reduce mod ℓ (`from_bytes_mod_order_wide`),
/// which is the standard, bias-free way to get a uniform scalar.
pub fn rand_scalar_os() -> Scalar {
    let mut wide = [0u8; 64];
    OsRng.fill_bytes(&mut wide);
    Scalar::from_bytes_mod_order_wide(&wide)
}

/// One guardian's long-lived key material after DKG.
#[derive(Clone, Debug)]
pub struct GuardianShare {
    /// 1-based guardian index `j` (the Shamir x-coordinate).
    pub index: u32,
    /// Additive key share `s_j = Σ_i f_i(j)` — secret, never leaves the guardian.
    pub share: Scalar,
}

/// The public result of the DKG: the group key and per-guardian verification
/// points. Distributed to everyone (including the chain, which stores `group_pub`).
#[derive(Clone, Debug)]
pub struct FederationPublic {
    pub n: u32,
    pub t: u32,
    /// `K = k·G`, the group mint public key. The on-chain redeem stores this.
    pub group_pub: [u8; 32],
    /// `S_j = s_j·G` for each guardian — lets anyone verify a partial signature.
    pub share_pubs: Vec<(u32, [u8; 32])>,
}

/// Full DKG output (secret shares + public data). In production each guardian
/// would hold only its own `GuardianShare`; here we return them all for the
/// single-process e2e and clearly label it.
pub struct DkgResult {
    pub guardians: Vec<GuardianShare>,
    pub public: FederationPublic,
    /// The reconstructed `k` — computed ONLY for test assertions ("nobody should
    /// hold this"); the protocol itself never materializes it on a guardian.
    pub k_for_tests: Scalar,
}

fn rand_scalar() -> Scalar {
    rand_scalar_os()
}

/// Evaluate polynomial `coeffs` (low-order first) at `x`, Horner's method.
fn poly_eval(coeffs: &[Scalar], x: Scalar) -> Scalar {
    let mut acc = Scalar::zero();
    for c in coeffs.iter().rev() {
        acc = acc * x + c;
    }
    acc
}

/// Lagrange coefficient `λ_j` at `x = 0` for signer set `signers` (the x-coords).
/// `λ_j = Π_{m≠j} (x_m) / (x_m − x_j)`.
pub fn lagrange_at_zero(signers: &[u32], j: u32) -> Scalar {
    let xj = Scalar::from(j as u64);
    let mut num = Scalar::one();
    let mut den = Scalar::one();
    for &m in signers {
        if m == j {
            continue;
        }
        let xm = Scalar::from(m as u64);
        num *= xm;
        den *= xm - xj;
    }
    num * den.invert()
}

/// Run a `t`-of-`n` joint-Feldman DKG. Returns each guardian's secret share plus
/// the public group key. Panics if `t==0 || t>n`.
///
/// This simulates the protocol in one process: it constructs every guardian's
/// polynomial, "delivers" and *verifies* every share against the Feldman
/// commitments (the `verify_share` check below is the real VSS soundness check),
/// then forms each additive share. No single guardian's polynomial reveals `k`.
pub fn dkg(n: u32, t: u32) -> DkgResult {
    assert!(t >= 1 && t <= n, "need 1 <= t <= n");

    // Each guardian i samples f_i of degree t-1 and its Feldman commitments.
    let mut polys: Vec<Vec<Scalar>> = Vec::with_capacity(n as usize);
    let mut commits: Vec<Vec<RistrettoPoint>> = Vec::with_capacity(n as usize);
    for _i in 0..n {
        let coeffs: Vec<Scalar> = (0..t).map(|_| rand_scalar()).collect();
        let comm: Vec<RistrettoPoint> = coeffs.iter().map(|c| c * G).collect();
        polys.push(coeffs);
        commits.push(comm);
    }

    // Each guardian j collects shares f_i(j) from every i and VERIFIES them
    // against i's Feldman commitments: f_i(j)·G == Σ_l j^l · A_{i,l}.
    let mut shares: Vec<Scalar> = Vec::with_capacity(n as usize);
    for j in 1..=n {
        let xj = Scalar::from(j as u64);
        let mut s_j = Scalar::zero();
        for i in 0..n as usize {
            let f_ij = poly_eval(&polys[i], xj);
            // Feldman check (real VSS soundness): reject a cheating dealer.
            assert!(
                verify_share(&commits[i], j, &f_ij),
                "Feldman VSS check failed for dealer {i} -> {j}"
            );
            s_j += f_ij;
        }
        shares.push(s_j);
    }

    // Group key K = Σ_i A_{i,0} = k·G ; per-guardian S_j = s_j·G.
    let group_point: RistrettoPoint = commits.iter().map(|c| c[0]).sum();
    let group_pub = group_point.compress().to_bytes();
    let share_pubs: Vec<(u32, [u8; 32])> = shares
        .iter()
        .enumerate()
        .map(|(idx, s)| ((idx as u32) + 1, (s * G).compress().to_bytes()))
        .collect();

    let guardians: Vec<GuardianShare> = shares
        .iter()
        .enumerate()
        .map(|(idx, s)| GuardianShare {
            index: (idx as u32) + 1,
            share: *s,
        })
        .collect();

    // k = Σ_i f_i(0) — for tests only.
    let k_for_tests: Scalar = polys.iter().map(|p| p[0]).sum();

    DkgResult {
        guardians,
        public: FederationPublic {
            n,
            t,
            group_pub,
            share_pubs,
        },
        k_for_tests,
    }
}

/// Feldman share check: `f_i(j)·G == Σ_l j^l · A_{i,l}`.
pub fn verify_share(commitments: &[RistrettoPoint], j: u32, share: &Scalar) -> bool {
    let xj = Scalar::from(j as u64);
    let mut rhs = RistrettoPoint::default(); // identity
    let mut xpow = Scalar::one();
    for a in commitments {
        rhs += xpow * a;
        xpow *= xj;
    }
    (share * G) == rhs
}

/// One guardian's partial blind signature on `B_`: `C_j = s_j·B_`.
///
/// Returns `(index, C_j_compressed)`. The federation needs `t` of these.
pub fn partial_blind_sign(
    guardian: &GuardianShare,
    b_compressed: &[u8; 32],
) -> Option<(u32, [u8; 32])> {
    let b_ = CompressedRistretto(*b_compressed).decompress()?;
    let c_j = guardian.share * b_;
    Some((guardian.index, c_j.compress().to_bytes()))
}

/// Combine `t` partial blind signatures into the BDHKE `C_ = k·B_` via Lagrange
/// interpolation in the exponent: `C_ = Σ_j λ_j · C_j`.
///
/// `partials` is `[(index, C_j_compressed), ...]`; uses their indices as the
/// signer set. Returns `None` on any malformed point.
pub fn combine_partial_sigs(partials: &[(u32, [u8; 32])]) -> Option<[u8; 32]> {
    let signers: Vec<u32> = partials.iter().map(|(i, _)| *i).collect();
    let mut acc = RistrettoPoint::default(); // identity
    for (idx, c_bytes) in partials {
        let c_j = CompressedRistretto(*c_bytes).decompress()?;
        let lambda = lagrange_at_zero(&signers, *idx);
        acc += lambda * c_j;
    }
    Some(acc.compress().to_bytes())
}

// ─── Threshold DLEQ (FROST-style distributed Schnorr over the shared k) ──────

/// A guardian's nonce commitment for one threshold-DLEQ round: `(D1_j, D2_j) =
/// (d_j·G, d_j·Y)`. Published so the aggregate nonce can be formed.
#[derive(Clone)]
pub struct NonceCommit {
    pub index: u32,
    d: Scalar, // kept by the guardian; exposed here only for the single-process sim
    pub d1: [u8; 32],
    pub d2: [u8; 32],
}

/// Round 1: guardian samples a fresh nonce `d_j` and commits `d_j·G`, `d_j·Y`.
pub fn dleq_nonce_commit(index: u32, y: &RistrettoPoint) -> NonceCommit {
    let d = rand_scalar();
    NonceCommit {
        index,
        d,
        d1: (d * G).compress().to_bytes(),
        d2: (d * y).compress().to_bytes(),
    }
}

/// Aggregate the per-signer nonce commitments into `R1 = Σ λ_j D1_j`,
/// `R2 = Σ λ_j D2_j`, and derive the Fiat–Shamir challenge `e` bound to the
/// statement `(K, Y, C)`.
fn aggregate_nonce_and_challenge(
    commits: &[NonceCommit],
    group_pub: &CompressedRistretto,
    y: &CompressedRistretto,
    c: &CompressedRistretto,
) -> Option<(RistrettoPoint, RistrettoPoint, Scalar)> {
    let signers: Vec<u32> = commits.iter().map(|c| c.index).collect();
    let mut r1 = RistrettoPoint::default();
    let mut r2 = RistrettoPoint::default();
    for nc in commits {
        let lambda = lagrange_at_zero(&signers, nc.index);
        r1 += lambda * CompressedRistretto(nc.d1).decompress()?;
        r2 += lambda * CompressedRistretto(nc.d2).decompress()?;
    }
    // Same challenge binding as crate::dleq::challenge — must match the verifier.
    let mut h = Sha512::new();
    h.update(b"eNULL-DLEQ-v1");
    h.update(G.compress().as_bytes());
    h.update(group_pub.as_bytes());
    h.update(y.as_bytes());
    h.update(c.as_bytes());
    h.update(r1.compress().as_bytes());
    h.update(r2.compress().as_bytes());
    let d = h.finalize();
    let mut wide = [0u8; 64];
    wide.copy_from_slice(&d);
    let e = Scalar::from_bytes_mod_order_wide(&wide);
    Some((r1, r2, e))
}

/// Produce a threshold DLEQ proof that `C = k·Y` under the group key, using `t`
/// guardians. Single-process orchestration of the two FROST rounds.
///
/// `signers` are the `GuardianShare`s participating (must be ≥ t distinct).
/// Returns the proof, the recovered `C` (so the caller can cross-check it equals
/// the combined blind-sig path), and `Y`.
pub fn threshold_dleq(
    signers: &[GuardianShare],
    public: &FederationPublic,
    secret: &[u8],
) -> DleqProof {
    let y = hash_to_curve(secret);
    let y_c = y.compress();
    let group_pub_c = CompressedRistretto(public.group_pub);

    // C = k·Y, reconstructed from partial point-mults s_j·Y (same Lagrange combine).
    let sig_idx: Vec<u32> = signers.iter().map(|g| g.index).collect();
    let mut c_point = RistrettoPoint::default();
    for g in signers {
        let lambda = lagrange_at_zero(&sig_idx, g.index);
        c_point += lambda * (g.share * y);
    }
    let c_c = c_point.compress();

    // Round 1: each signer commits a nonce.
    let commits: Vec<NonceCommit> = signers
        .iter()
        .map(|g| dleq_nonce_commit(g.index, &y))
        .collect();
    let (_r1, _r2, e) =
        aggregate_nonce_and_challenge(&commits, &group_pub_c, &y_c, &c_c).expect("agg nonce");

    // Round 2: each signer returns z_j = d_j + e·s_j ; aggregate z = Σ λ_j z_j.
    let mut z = Scalar::zero();
    for (g, nc) in signers.iter().zip(commits.iter()) {
        let lambda = lagrange_at_zero(&sig_idx, g.index);
        let z_j = nc.d + e * g.share;
        z += lambda * z_j;
    }

    DleqProof {
        e: e.to_bytes(),
        z: z.to_bytes(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::bdhke::{blind, public_key, unblind, verify_token, Token};
    use crate::dleq::verify_dleq;

    #[test]
    fn dkg_group_key_is_consistent() {
        let res = dkg(5, 3);
        // K must equal k·G for the (test-only) reconstructed k.
        assert_eq!(res.public.group_pub, public_key(&res.k_for_tests));
        assert_eq!(res.guardians.len(), 5);
    }

    #[test]
    fn t_of_n_reconstructs_mint_signature() {
        // 3-of-5 federation must reconstruct the SAME C_ a single mint with key k
        // would have produced.
        let res = dkg(5, 3);
        let secret = b"fed-token".to_vec();
        let bm = blind(&secret, rand_scalar_os());

        // Pick 3 guardians (indices 1,3,5) — any t of n.
        let chosen = [&res.guardians[0], &res.guardians[2], &res.guardians[4]];
        let partials: Vec<(u32, [u8; 32])> = chosen
            .iter()
            .map(|g| partial_blind_sign(g, &bm.b_).unwrap())
            .collect();
        let c_blind = combine_partial_sigs(&partials).unwrap();

        // Equals the single-mint blind sig under the (test-only) k.
        let single = crate::bdhke::sign_blinded(&res.k_for_tests, &bm.b_).unwrap();
        assert_eq!(c_blind, single, "threshold C_ must equal single-mint C_");

        // And the unblinded token verifies under k.
        let k_pub = res.public.group_pub;
        let c = unblind(&c_blind, &k_pub, &bm.r).unwrap();
        let token = Token { secret, c };
        assert!(verify_token(&res.k_for_tests, &token));
    }

    #[test]
    fn fewer_than_t_cannot_reconstruct() {
        // Only 2 of a 3-of-5 cooperate: the combined "signature" must NOT equal
        // the real k·B_ — i.e. it does not produce a valid token.
        let res = dkg(5, 3);
        let secret = b"under-threshold".to_vec();
        let bm = blind(&secret, rand_scalar_os());

        let chosen = [&res.guardians[0], &res.guardians[1]]; // only 2
        let partials: Vec<(u32, [u8; 32])> = chosen
            .iter()
            .map(|g| partial_blind_sign(g, &bm.b_).unwrap())
            .collect();
        let c_blind = combine_partial_sigs(&partials).unwrap();

        let single = crate::bdhke::sign_blinded(&res.k_for_tests, &bm.b_).unwrap();
        assert_ne!(
            c_blind, single,
            "fewer than t guardians MUST NOT reconstruct the mint signature"
        );

        let k_pub = res.public.group_pub;
        let c = unblind(&c_blind, &k_pub, &bm.r).unwrap();
        let token = Token { secret, c };
        assert!(
            !verify_token(&res.k_for_tests, &token),
            "under-threshold token must be invalid"
        );
    }

    #[test]
    fn threshold_dleq_verifies_under_group_key() {
        let res = dkg(5, 3);
        let secret = b"dleq-token";
        let chosen = vec![
            res.guardians[1].clone(),
            res.guardians[2].clone(),
            res.guardians[4].clone(),
        ];
        let proof = threshold_dleq(&chosen, &res.public, secret);

        // Recompute Y and C the on-chain way and verify the DLEQ under K.
        let y = hash_to_curve(secret).compress().to_bytes();
        let c = (res.k_for_tests * hash_to_curve(secret))
            .compress()
            .to_bytes();
        assert!(verify_dleq(&res.public.group_pub, &y, &c, &proof));
    }

    #[test]
    fn threshold_dleq_different_signer_set_same_proof_validity() {
        // Any valid t-subset must yield a DLEQ that verifies (robustness).
        let res = dkg(5, 3);
        let secret = b"robust";
        for set in [[0usize, 1, 2], [1, 3, 4], [0, 2, 4]] {
            let chosen: Vec<_> = set.iter().map(|&i| res.guardians[i].clone()).collect();
            let proof = threshold_dleq(&chosen, &res.public, secret);
            let y = hash_to_curve(secret).compress().to_bytes();
            let c = (res.k_for_tests * hash_to_curve(secret))
                .compress()
                .to_bytes();
            assert!(
                verify_dleq(&res.public.group_pub, &y, &c, &proof),
                "set {:?}",
                set
            );
        }
    }
}
