use borsh::{BorshDeserialize, BorshSerialize};
use ark_bn254::g1::G1Affine as G1;
use ark_serialize::{CanonicalDeserialize, CanonicalSerialize, Compress, Validate};
use groth16_solana::groth16::Groth16Verifier;
use solana_program::{
    account_info::{next_account_info, AccountInfo},
    entrypoint,
    entrypoint::ProgramResult,
    keccak,
    msg,
    program::{invoke, invoke_signed},
    program_error::ProgramError,
    pubkey::Pubkey,
    rent::Rent,
    system_instruction,
};
use std::ops::Neg;
use verifying_key::VERIFYINGKEY;
// use nebula_compression::NebulaCompressor; // TODO: Integrate compression later

// -----------------------------------------------------------------------------
// ⚙️ CONFIGURATION & CONSTANTS
// -----------------------------------------------------------------------------

/// The Verifying Key generated by your Circom circuit.
/// Ideally, keep this in a separate 'verifying_key.rs' file and import it.
pub mod verifying_key;

/// Seed used to derive Nullifier PDAs.
/// Prevents double-spending by tracking consumed notes.
const NULLIFIER_SEED: &[u8] = b"pdx_nullifier";

/// Seed for the Protocol Vault PDA.
/// This account MUST be pre-funded to pay relayers.
const VAULT_SEED: &[u8] = b"pdx_vault";

/// Dynamic fee policy used for relayer payouts.
/// base_fee_lamports: fixed minimum fee component
/// fee_bps: variable component in basis points of withdrawal amount
/// min_settle_lamports: values below this should be netted/streamed off-chain (not rejected on-chain)
#[derive(BorshSerialize, BorshDeserialize, Debug, Clone, Copy)]
pub struct FeePolicy {
    pub base_fee_lamports: u64,
    pub fee_bps: u16,
    pub min_settle_lamports: u64,
}

/// Default policy tuned for micropayment compatibility.
const DEFAULT_FEE_POLICY: FeePolicy = FeePolicy {
    base_fee_lamports: 5_000,  // 0.000005 SOL
    fee_bps: 50,               // 0.50%
    min_settle_lamports: 0,    // never hard-reject tiny withdrawals
};

const NR_PUBLIC_INPUTS: usize = VERIFYINGKEY.nr_pubinputs - 1;

// -----------------------------------------------------------------------------
// 📦 INSTRUCTION DESERIALIZATION
// -----------------------------------------------------------------------------

#[derive(BorshSerialize, BorshDeserialize, Debug)]
pub enum DarkInstruction {
    /// Standard Deposit (Public)
    /// Users deposit SOL/Tokens to mint a private note.
    Deposit {
        amount: u64,
        commitment: [u8; 32]
    },

    /// Private Withdrawal (The "Null" Transaction)
    /// ZK-Verified withdrawal from privacy pool to recipient.
    Withdraw {
        proof: Vec<u8>,             // Groth16 Proof (A[64], B[128], C[64])
        root: [u8; 32],             // Merkle Root
        nullifier_asset: [u8; 32],  // Unique ID for Asset Note
        nullifier_fee: [u8; 32],    // Unique ID for Fee Note
        new_commitment: [u8; 32],   // New Note Output (optional)
        asset_id_hash: [u8; 32],    // INTEGRITY LOCK: keccak256(recipient + amount)
        recipient: Pubkey,          // The recipient who will receive the SOL
        amount: u64,                // Amount to withdraw from pool
    },
}

// -----------------------------------------------------------------------------
// 🚀 ENTRYPOINT
// -----------------------------------------------------------------------------

entrypoint!(process_instruction);

pub fn process_instruction(
    program_id: &Pubkey,
    accounts: &[AccountInfo],
    ix_data: &[u8],
) -> ProgramResult {
    // Attempt to parse instruction
    let ix = DarkInstruction::try_from_slice(ix_data)
        .map_err(|_| ProgramError::InvalidInstructionData)?;

    match ix {
        DarkInstruction::Deposit { amount, commitment } => {
            msg!("PDX_INFO: Deposit Request: {} lamports", amount);
            msg!("PDX_INFO: Commitment: {:?}", commitment);

            // In a real implementation, you would transfer funds from User -> Vault here.
            Ok(())
        }

        DarkInstruction::Withdraw {
            proof,
            root,
            nullifier_asset,
            nullifier_fee,
            new_commitment,
            asset_id_hash,
            recipient,
            amount,
        } => process_withdraw(
            program_id,
            accounts,
            proof,
            root,
            nullifier_asset,
            nullifier_fee,
            new_commitment,
            asset_id_hash,
            recipient,
            amount,
        ),
    }
}

// -----------------------------------------------------------------------------
// 🛡️ CORE LOGIC: PROCESS DEPOSIT
// -----------------------------------------------------------------------------

fn process_deposit(
    program_id: &Pubkey,
    accounts: &[AccountInfo],
    amount: u64,
    commitment: [u8; 32],
) -> ProgramResult {
    let acc_iter = &mut accounts.iter();

    // --- 1. ACCOUNT DECODING ---
    let depositor = next_account_info(acc_iter)?;     // [0] Depositor (Signer, pays amount)
    let vault_pda = next_account_info(acc_iter)?;     // [1] Vault PDA (Receives deposit)
    let system = next_account_info(acc_iter)?;        // [2] System Program

    // --- 2. VALIDATION ---
    let (vault_addr, vault_bump) = Pubkey::find_program_address(&[VAULT_SEED], program_id);
    if *vault_pda.key != vault_addr {
        msg!("PDX_ERROR: Invalid Vault PDA provided.");
        return Err(ProgramError::InvalidArgument);
    }

    // Reject only zero-value deposits. Micropayment batching happens off-chain.
    if amount == 0 {
        msg!("PDX_ERROR: Deposit amount must be > 0 lamports");
        return Err(ProgramError::InvalidArgument);
    }

    // --- 3. EXECUTE DEPOSIT ---
    msg!("PDX_INFO: Processing deposit of {} lamports", amount);

    // Transfer from depositor to vault
    invoke(
        &system_instruction::transfer(
            depositor.key,
            vault_pda.key,
            amount,
        ),
        &[depositor.clone(), vault_pda.clone(), system.clone()],
    )?;

    msg!("PDX_SUCCESS: Deposit completed. Commitment: {:?}", commitment);
    Ok(())
}

// -----------------------------------------------------------------------------
// 🛡️ CORE LOGIC: PROCESS WITHDRAWAL
// -----------------------------------------------------------------------------

fn process_withdraw(
    program_id: &Pubkey,
    accounts: &[AccountInfo],
    proof: Vec<u8>,
    root: [u8; 32],
    nullifier_asset: [u8; 32],
    nullifier_fee: [u8; 32],
    new_commitment: [u8; 32],
    asset_id_hash: [u8; 32],
    recipient: Pubkey,
    amount: u64,
) -> ProgramResult {
    let acc_iter = &mut accounts.iter();

    // --- 1. ACCOUNT DECODING ---

    let payer = next_account_info(acc_iter)?;          // [0] Relayer (Signer, receives fee)
    let recipient = next_account_info(acc_iter)?;      // [1] Recipient (Writable, receives SOL)
    let null_asset_pda = next_account_info(acc_iter)?; // [2] Asset Nullifier PDA (Writable)
    let null_fee_pda = next_account_info(acc_iter)?;   // [3] Fee Nullifier PDA (Writable)
    let vault_pda = next_account_info(acc_iter)?;      // [4] Vault PDA (Source of withdrawal + fee)
    let system = next_account_info(acc_iter)?;         // [5] System Program

    // --- 2. HARDENING: VAULT HEALTH CHECK ---

    // Fail FAST if the relayer cannot be paid.
    // This protects the user from burning a proof for no reason.

    let (vault_addr, vault_bump) = Pubkey::find_program_address(&[VAULT_SEED], program_id);
    if *vault_pda.key != vault_addr {
        msg!("PDX_ERROR: Invalid Vault PDA provided.");
        return Err(ProgramError::InvalidArgument);
    }

    let relayer_fee = calculate_relayer_fee(amount, DEFAULT_FEE_POLICY)?;
    let total_needed = amount
        .checked_add(relayer_fee)
        .ok_or(ProgramError::InvalidArgument)?;
    if **vault_pda.lamports.borrow() < total_needed {
        msg!("PDX_ERROR: Insufficient vault balance! Need {} lamports, have {}", total_needed, **vault_pda.lamports.borrow());
        return Err(ProgramError::InsufficientFunds);
    }

    // Check withdrawal amount limits
    if amount == 0 {
        msg!("PDX_ERROR: Withdrawal amount must be > 0 lamports");
        return Err(ProgramError::InvalidArgument);
    }
    if amount > 10_000_000_000 { // 10 SOL maximum per withdrawal
        msg!("PDX_ERROR: Withdrawal too large (maximum 10 SOL)");
        return Err(ProgramError::InvalidArgument);
    }

    if amount < DEFAULT_FEE_POLICY.min_settle_lamports {
        msg!(
            "PDX_INFO: Amount below min_settle_lamports={}, expecting off-chain netting/streaming",
            DEFAULT_FEE_POLICY.min_settle_lamports
        );
    }

    // --- 3. SECURITY: INTEGRITY VERIFICATION ---

    // The ZK proof verifies 'asset_id_hash'. We must ensure recipient + amount matches it.
    let mut integrity_data = recipient.key.to_bytes().to_vec();
    integrity_data.extend_from_slice(&amount.to_le_bytes());
    let calculated_hash = keccak::hash(&integrity_data);
    if calculated_hash.to_bytes() != asset_id_hash {
        msg!("PDX_CRITICAL: Integrity Mismatch!");
        msg!("Expected: {:?}", asset_id_hash);
        msg!("Actual:   {:?}", calculated_hash.to_bytes());
        return Err(ProgramError::InvalidInstructionData);
    }

    // --- 4. SECURITY: INPUT VALIDATION ---

    validate_public_inputs(&root, &nullifier_asset, &nullifier_fee, &new_commitment, &asset_id_hash)?;

    // --- 5. SECURITY: ZK PROOF VERIFICATION (The Shield) ---

    // This MUST happen before any state change.
    let public_inputs = [root, nullifier_asset, nullifier_fee, new_commitment, asset_id_hash];
    if !verify_proof(&proof, &public_inputs)? {
        msg!("PDX_CRITICAL: ZK Proof Verification Failed.");
        return Err(ProgramError::InvalidArgument);
    }

    // --- 6. SECURITY: NULLIFIER UNIQUENESS ---

    // Ensure these notes haven't been spent before.
    verify_nullifier_unused(program_id, null_asset_pda, &nullifier_asset)?;
    verify_nullifier_unused(program_id, null_fee_pda, &nullifier_fee)?;

    // =====================================================================
    // ⚡ POINT OF NO RETURN: STATE MUTATION STARTS HERE
    // =====================================================================

    // --- 7. CONSUME NULLIFIERS (Burn the Notes) ---

    // We create the PDA accounts and mark them as "Consumed".
    consume_nullifier(program_id, payer, null_asset_pda, system, &nullifier_asset)?;
    consume_nullifier(program_id, payer, null_fee_pda, system, &nullifier_fee)?;

    // --- 8. EXECUTE WITHDRAWAL (The Real Transfer) ---

    // Transfer SOL from Vault -> Recipient
    msg!("PDX_INFO: Withdrawing {} lamports to recipient: {:?}", amount, recipient.key);
    invoke_signed(
        &system_instruction::transfer(
            vault_pda.key,
            recipient.key,
            amount,
        ),
        &[vault_pda.clone(), recipient.clone(), system.clone()],
        &[&[VAULT_SEED, &[vault_bump]]],
    )?;

    // --- 9. PAY THE RELAYER (The Incentive) ---

    // Atomic transfer from Vault -> Relayer.
    msg!("PDX_INFO: Paying Relayer: {} lamports", relayer_fee);
    invoke_signed(
        &system_instruction::transfer(
            vault_pda.key,
            payer.key,
            relayer_fee
        ),
        &[vault_pda.clone(), payer.clone(), system.clone()],
        &[&[VAULT_SEED, &[vault_bump]]]
    )?;

    msg!("PDX_SUCCESS: Withdrawal of {} lamports completed to {:?}", amount, recipient.key);
    msg!("PDX_SUCCESS: Privacy preserved - no wallet linkage possible!");
    Ok(())
}

// -----------------------------------------------------------------------------
// 🛠️ HELPER FUNCTIONS
// -----------------------------------------------------------------------------

fn validate_public_inputs(
    root: &[u8; 32],
    nullifier_asset: &[u8; 32],
    nullifier_fee: &[u8; 32],
    new_commitment: &[u8; 32],
    asset_id_hash: &[u8; 32],
) -> ProgramResult {
    let inputs = [root, nullifier_asset, nullifier_fee, new_commitment, asset_id_hash];
    for (i, input) in inputs.iter().enumerate() {
        // Reject all-zero inputs (common attack vector)
        if input.iter().all(|&x| x == 0) {
            msg!("PDX_ERROR: Zero input detected at index {}", i);
            return Err(ProgramError::InvalidArgument);
        }
    }

    // Asset and Fee nullifiers must be distinct
    if nullifier_asset == nullifier_fee {
        msg!("PDX_ERROR: Identical Nullifiers.");
        return Err(ProgramError::InvalidArgument);
    }

    Ok(())
}

fn verify_nullifier_unused(
    program_id: &Pubkey,
    pda_account: &AccountInfo,
    nullifier: &[u8; 32],
) -> ProgramResult {
    let (expected_pda, _bump) = Pubkey::find_program_address(&[NULLIFIER_SEED, nullifier], program_id);

    if expected_pda != *pda_account.key {
        msg!("PDX_ERROR: Invalid Nullifier PDA address.");
        return Err(ProgramError::InvalidArgument);
    }

    // If account has data, it means it was already initialized (Spent)
    if !pda_account.data_is_empty() {
        msg!("PDX_ERROR: Double Spend Detected! Nullifier already used.");
        return Err(ProgramError::AccountAlreadyInitialized);
    }
    Ok(())
}

fn consume_nullifier<'a>(
    prog_id: &Pubkey,
    payer: &AccountInfo<'a>,
    pda: &AccountInfo<'a>,
    sys: &AccountInfo<'a>,
    null: &[u8; 32]
) -> ProgramResult {
    let (key, bump) = Pubkey::find_program_address(&[NULLIFIER_SEED, null], prog_id);

    if key != *pda.key {
        return Err(ProgramError::InvalidArgument);
    }
    // Create the account with exactly 1 byte of space.
    // This prevents "Fake Account" attacks where data is empty but account exists.
    invoke_signed(
        &system_instruction::create_account(
            payer.key,
            pda.key,
            Rent::default().minimum_balance(1), // Rent for 1 byte
            1,                                  // Space: 1 byte
            prog_id
        ),
        &[payer.clone(), pda.clone(), sys.clone()],
        &[&[NULLIFIER_SEED, null, &[bump]]]
    )?;

    // Explicitly write "1" to mark as consumed.
    let mut data = pda.try_borrow_mut_data()?;
    data[0] = 1;
    Ok(())
}

fn change_endianness(bytes: &[u8]) -> Vec<u8> {
    let mut vec = Vec::with_capacity(bytes.len());
    for chunk in bytes.chunks(32) {
        for byte in chunk.iter().rev() {
            vec.push(*byte);
        }
    }
    vec
}

fn verify_proof(
    proof_bytes: &[u8],
    public_inputs: &[[u8; 32]],
) -> Result<bool, ProgramError> {
    if proof_bytes.len() != 256 {
        msg!("PDX_ERROR: Invalid Proof Length.");
        return Err(ProgramError::InvalidArgument);
    }
    if public_inputs.len() > NR_PUBLIC_INPUTS {
        msg!(
            "PDX_ERROR: Too many public inputs. Got {}, max {}.",
            public_inputs.len(),
            NR_PUBLIC_INPUTS
        );
        return Err(ProgramError::InvalidArgument);
    }

    let mut prepared_public_inputs = [[0u8; 32]; NR_PUBLIC_INPUTS];
    prepared_public_inputs[..public_inputs.len()].copy_from_slice(public_inputs);

    let proof_a: G1 = G1::deserialize_with_mode(
        &*[&change_endianness(&proof_bytes[0..64]), &[0u8][..]].concat(),
        Compress::No,
        Validate::Yes,
    )
    .map_err(|_| {
        msg!("PDX_ERROR: Invalid Proof A encoding.");
        ProgramError::InvalidArgument
    })?;

    let mut proof_a_neg = [0u8; 65];
    proof_a
        .neg()
        .x
        .serialize_with_mode(&mut proof_a_neg[..32], Compress::No)
        .map_err(|_| {
            msg!("PDX_ERROR: Failed to serialize negated proof A.x.");
            ProgramError::InvalidArgument
        })?;
    proof_a
        .neg()
        .y
        .serialize_with_mode(&mut proof_a_neg[32..], Compress::No)
        .map_err(|_| {
            msg!("PDX_ERROR: Failed to serialize negated proof A.y.");
            ProgramError::InvalidArgument
        })?;

    let proof_a: [u8; 64] = change_endianness(&proof_a_neg[..64])
        .try_into()
        .map_err(|_| {
            msg!("PDX_ERROR: Invalid negated proof A length.");
            ProgramError::InvalidArgument
        })?;
    let proof_b: [u8; 128] = proof_bytes[64..192].try_into().map_err(|_| {
        msg!("PDX_ERROR: Invalid Proof B length.");
        ProgramError::InvalidArgument
    })?;
    let proof_c: [u8; 64] = proof_bytes[192..256].try_into().map_err(|_| {
        msg!("PDX_ERROR: Invalid Proof C length.");
        ProgramError::InvalidArgument
    })?;

    let mut verifier = Groth16Verifier::<NR_PUBLIC_INPUTS>::new(
        &proof_a,
        &proof_b,
        &proof_c,
        &prepared_public_inputs,
        &VERIFYINGKEY,
    )
    .map_err(|err| {
        msg!("PDX_ERROR: Verifier init failed: {:?}", err);
        ProgramError::InvalidArgument
    })?;

    match verifier.verify() {
        Ok(result) => Ok(result),
        Err(err) => {
            msg!("PDX_ERROR: Groth16 verification failed: {:?}", err);
            Ok(false)
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn fee_policy_uses_base_plus_bps() {
        let policy = FeePolicy {
            base_fee_lamports: 5_000,
            fee_bps: 50,
            min_settle_lamports: 0,
        };

        let fee = calculate_relayer_fee(1_000_000, policy).unwrap();
        // 5_000 base + 0.5% of 1_000_000 = 10_000
        assert_eq!(fee, 10_000);
    }

    #[test]
    fn default_policy_does_not_force_min_settle_rejection() {
        assert_eq!(DEFAULT_FEE_POLICY.min_settle_lamports, 0);
        let fee = calculate_relayer_fee(10, DEFAULT_FEE_POLICY).unwrap();
        assert!(fee >= DEFAULT_FEE_POLICY.base_fee_lamports);
    }
}

fn calculate_relayer_fee(amount: u64, policy: FeePolicy) -> Result<u64, ProgramError> {
    let bps_fee = amount
        .checked_mul(policy.fee_bps as u64)
        .ok_or(ProgramError::InvalidArgument)?
        / 10_000;

    policy
        .base_fee_lamports
        .checked_add(bps_fee)
        .ok_or(ProgramError::InvalidArgument)
}
